CREATE TABLE "HR"."JOBS_BK" 
(	"JOB_ID" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
"JOB_TITLE" VARCHAR2(35 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
"MIN_SALARY" NUMBER(6,0), 
"MAX_SALARY" NUMBER(6,0)
)  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

COMMENT ON COLUMN "HR"."JOBS_BK"."JOB_ID" IS 'Primary key of jobs table.';
COMMENT ON COLUMN "HR"."JOBS_BK"."JOB_TITLE" IS 'A not null column that shows job title, e.g. AD_VP, FI_ACCOUNTANT';
COMMENT ON COLUMN "HR"."JOBS_BK"."MIN_SALARY" IS 'Minimum salary for a job title.';
COMMENT ON COLUMN "HR"."JOBS_BK"."MAX_SALARY" IS 'Maximum salary for a job title';
COMMENT ON TABLE "HR"."JOBS_BK"  IS 'jobs table with job titles and salary ranges.
References with employees and job_history table.';