CREATE VIEW hr.employees_jobs_v AS
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.EMAIL, e.PHONE_NUMBER, 
       e.HIRE_DATE, e.JOB_ID, e.SALARY, e.COMMISSION_PCT, e.MANAGER_ID, e.DEPARTMENT_ID,
       j.JOB_TITLE, j.MIN_SALARY, j.MAX_SALARY
FROM HR.EMPLOYEES_BK e
JOIN HR.JOBS_BK j ON e.JOB_ID = j.JOB_ID;
